import type { Metadata } from "next";
import localFont from "next/font/local";
import Head from "next/head";  // Importando o componente Head
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Definindo o título da página */}
        <title>{metadata.title}</title>
        {/* Definindo a descrição da página */}
        <meta name="description" content={metadata.description} />
        {/* Definindo a charset */}
        <meta charSet="UTF-8" />
        {/* Definindo o viewport para responsividade */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Links para fontes externas ou outras tags <head> que você precisar */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
